name: Patch VBMeta (ARM Emulation)

on:
  workflow_dispatch:
    inputs:
      ARCHITECTURE:
        description: 'Architecture'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - x86_64
          - arm64-v8a

permissions:
  contents: write

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3.1.0

      - name: Show OS Info
        run: uname -a

      - name: Install QEMU for ARM64
        run: |
          sudo apt update
          sudo apt install -y qemu-user

      - name: Confirm file type
        run: |
          file ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification

      - name: Emulate and Run Binary with QEMU
        if: ${{ github.event.inputs.ARCHITECTURE == 'arm64-v8a' }}
        run: |
          chmod +x ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification
          qemu-aarch64 -L /usr/aarch64-linux-gnu \
            ./${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification vbmeta.img

      - name: Run natively (x86_64 only)
        if: ${{ github.event.inputs.ARCHITECTURE == 'x86_64' }}
        run: |
          chmod +x x86_64/vbmeta-disable-verification
          ./x86_64/vbmeta-disable-verification vbmeta.img

      - name: Upload to Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: vbmeta.img
          Name: Patched VBMeta
          draft: false
          prerelease: true
          tag: ${{ github.run_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Archivo vbmeta.img parchado con binario ${{ github.event.inputs.ARCHITECTURE }}
